# Copyright cloudscale.ch
# Copyright 2018 DigitalOcean
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Configuration to deploy release version of the CSI cloudscale.ch
# plugin (https://github.com/cloudscale-ch/csi-cloudscale) compatible with
# Kubernetes >=v1.13.0
#
# example usage: kubectl create -f <this_file>

####################################################
###########                             ############
###########  CSI Node and Driver CRDs   ############
###########                             ############
####################################################
---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: csinodeinfos.csi.storage.k8s.io
spec:
  group: csi.storage.k8s.io
  names:
    kind: CSINodeInfo
    plural: csinodeinfos
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        csiDrivers:
          description: List of CSI drivers running on the node and their properties.
          items:
            properties:
              driver:
                description: The CSI driver that this object refers to.
                type: string
              nodeID:
                description: The node from the driver point of view.
                type: string
              topologyKeys:
                description: List of keys supported by the driver.
                items:
                  type: string
                type: array
          type: array
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

---

##########################################
###########                   ############
###########   Storage Class   ############
###########                   ############
##########################################

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cloudscale-volume-ssd
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ch.cloudscale.csi
parameters:
  csi.cloudscale.ch/volume-type: ssd

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cloudscale-volume-bulk
  namespace: kube-system
provisioner: ch.cloudscale.csi
parameters:
  csi.cloudscale.ch/volume-type: bulk

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cloudscale-volume-ssd-luks
  namespace: kube-system
provisioner: ch.cloudscale.csi
parameters:
  csi.cloudscale.ch/volume-type: ssd
  csi.cloudscale.ch/luks-encrypted: "true"
  csi.cloudscale.ch/luks-cipher: "aes-xts-plain64"
  csi.cloudscale.ch/luks-key-size: "512"
  csiNodeStageSecretNamespace: ${pvc.namespace}
  csiNodeStageSecretName: ${pvc.name}-luks-key

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cloudscale-volume-bulk-luks
  namespace: kube-system
provisioner: ch.cloudscale.csi
parameters:
  csi.cloudscale.ch/volume-type: bulk
  csi.cloudscale.ch/luks-encrypted: "true"
  csi.cloudscale.ch/luks-cipher: "aes-xts-plain64"
  csi.cloudscale.ch/luks-key-size: "512"
  csiNodeStageSecretNamespace: ${pvc.namespace}
  csiNodeStageSecretName: ${pvc.name}-luks-key

---

##############################################
###########                       ############
###########   Controller plugin   ############
###########                       ############
##############################################

kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-cloudscale-controller
  namespace: kube-system
spec:
  serviceName: "csi-cloudscale"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-cloudscale-controller
        role: csi-cloudscale
    spec:
      hostNetwork: true
      priorityClassName: system-cluster-critical
      serviceAccount: csi-cloudscale-controller-sa
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.0.1
          imagePullPolicy: "Always"
          args:
            - "--provisioner=ch.cloudscale.csi"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.1
          imagePullPolicy: "Always"
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-cluster-driver-registrar
          image: quay.io/k8scsi/csi-cluster-driver-registrar:v1.0.1
          args:
            - "--v=5"
            - "--pod-info-mount-version=\"v1\""
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-cloudscale-plugin
          image: cloudscalech/cloudscale-csi-plugin:dev
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--url=$(CLOUDSCALE_API_URL)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: CLOUDSCALE_API_URL
              value: https://api.cloudscale.ch/
            - name: CLOUDSCALE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudscale
                  key: access-token
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-cloudscale-controller-sa
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cloudscale-provisioner-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]
  # cluster-driver-registrar currently needs permissions to create the CSIDriver CRD
  # see https://github.com/kubernetes-csi/cluster-driver-registrar/issues/3
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create"]


---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cloudscale-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: csi-cloudscale-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-cloudscale-provisioner-role
  apiGroup: rbac.authorization.k8s.io

---
# Attacher must be able to work with PVs, nodes and VolumeAttachments
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cloudscale-attacher-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cloudscale-attacher-binding
subjects:
  - kind: ServiceAccount
    name: csi-cloudscale-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-cloudscale-attacher-role
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cloudscale-cluster-driver-registrar-role
rules:
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csidrivers"]
    verbs: ["create", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cloudscale-cluster-driver-registrar-binding
subjects:
  - kind: ServiceAccount
    name: csi-cloudscale-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-cloudscale-cluster-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io

---


########################################
###########                 ############
###########   Node plugin   ############
###########                 ############
########################################

kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-cloudscale-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-cloudscale-node
  template:
    metadata:
      labels:
        app: csi-cloudscale-node
        role: csi-cloudscale
    spec:
      priorityClassName: system-node-critical
      serviceAccount: csi-cloudscale-node-sa
      hostNetwork: true
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/csi.cloudscale.ch /registration/csi.cloudscale.ch-reg.sock"]
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/csi.cloudscale.ch/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
            - name: registration-dir
              mountPath: /registration/
        - name: csi-cloudscale-plugin
          image: cloudscalech/cloudscale-csi-plugin:dev
          imagePullPolicy: "Always"
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--url=$(CLOUDSCALE_API_URL)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: CLOUDSCALE_API_URL
              value: https://api.cloudscale.ch/
            - name: CLOUDSCALE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudscale
                  key: access-token
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              # needed so that any mounts setup inside this container are
              # propagated back to the host machine.
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
            - name: tmpfs
              mountPath: /tmp
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.cloudscale.ch
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
        # to make sure temporary stored luks keys never touch a disk
        - name: tmpfs
          emptyDir:
            medium: Memory

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-cloudscale-node-sa
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cloudscale-driver-registrar-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cloudscale-driver-registrar-binding
subjects:
  - kind: ServiceAccount
    name: csi-cloudscale-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-cloudscale-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io
