version: 2
updates:
  # Check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Check for Go module updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    groups:
      k8s:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      all-minor-patch:
        update-types:
          - "minor"
          - "patch"
    cooldown:
      default-days: 7

  # Check for helm updates
  - package-ecosystem: "helm"
    directory: "/charts/csi-cloudscale"
    schedule:
      interval: "weekly"

  # Check docker base image updates
  - package-ecosystem: "docker"
    directory: "/cmd/cloudscale-csi-plugin"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  # Check docker side-car containers in helm updates
  - package-ecosystem: "docker"
    directory: "/charts/csi-cloudscale"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
