apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pod-bulk-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: cloudscale-volume-bulk
